// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBTD32NlmPg_ZqPyvzcPLXff6IJ9gc8Tzs',
    appId: '1:913430737563:web:e9760e8a386c8bcc660c3e',
    messagingSenderId: '913430737563',
    projectId: 'cosmicpages-7d729',
    authDomain: 'cosmicpages-7d729.firebaseapp.com',
    storageBucket: 'cosmicpages-7d729.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA1xgcRFTBjjBxUwtHXWtckYo8ecwMXfF0',
    appId: '1:913430737563:android:67432235eea2187e660c3e',
    messagingSenderId: '913430737563',
    projectId: 'cosmicpages-7d729',
    storageBucket: 'cosmicpages-7d729.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBTD32NlmPg_ZqPyvzcPLXff6IJ9gc8Tzs',
    appId: '1:913430737563:web:db09e05edb630a1a660c3e',
    messagingSenderId: '913430737563',
    projectId: 'cosmicpages-7d729',
    authDomain: 'cosmicpages-7d729.firebaseapp.com',
    storageBucket: 'cosmicpages-7d729.firebasestorage.app',
  );
}
